on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: actions/neith-hello@v1
        with:
          who-to-greet: 'Alex'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
